config/routes.rb
Bankroll::Application.routes.draw do
  devise_for :users
  resources :users, path: 'user_admin'

  resources :variants

  resources :casinos

  resources :public_casinos, only: :index do
    collection do
      put :set
    end
  end

  resources :games, except: :show do
    collection do
      post :import
      get :prepare_import
    end
  end

  resources :stats

  root :to => 'stats#index'

end

app/models/casino.rb
class Casino < ActiveRecord::Base
  attr_accessible :name, :public
  has_many :games, :dependent => :destroy
  belongs_to :user

  validates :name, presence: true

  def prizes_sum(user)
    games.where(:user_id => user.id).sum(:prize) - games.where(:user_id => user.id).sum(:buyin)
  end

  def self.with_name(name)
    where('name LIKE ?', name).first_or_create(name: name)
  end

  def self.set_visibility(params)
    update_all(visible: false)
    where(id: params).update_all(visible: true)
  end

  scope :for_user_and_visible, lambda { |user_id| where("user_id = ? OR (visible = ? AND public = ?)", user_id, true, true) }
end

app/controllers/casinos_controller.rb
class CasinosController < ApplicationController
  # GET /casinos
  # GET /casinos.json
  def index
    @casinos = current_user.casinos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casinos }
    end
  end

  # GET /casinos/1
  # GET /casinos/1.json
  def show
    @casino = Casino.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @casino }
    end
  end

  # GET /casinos/new
  # GET /casinos/new.json
  def new
    @casino = Casino.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @casino }
    end
  end

  # GET /casinos/1/edit
  def edit
    @casino = Casino.find(params[:id])
  end

  # POST /casinos
  # POST /casinos.json
  def create
    @casino = Casino.new(params[:casino])
    @casino.user_id = current_user.id
    @casino.visible = true

    respond_to do |format|
      if @casino.save
        format.html { redirect_to @casino, notice: 'Casino was successfully created.' }
        format.json { render json: @casino, status: :created, location: @casino }
      else
        format.html { render action: "new" }
        format.json { render json: @casino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casinos/1
  # PUT /casinos/1.json
  def update
    @casino = Casino.find(params[:id])

    respond_to do |format|
      if @casino.update_attributes(params[:casino])
        format.html { redirect_to @casino, notice: 'Casino was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @casino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casinos/1
  # DELETE /casinos/1.json
  def destroy
    @casino = Casino.find(params[:id])
    @casino.destroy

    respond_to do |format|
      format.html { redirect_to casinos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/casinos_helper.rb
module CasinosHelper
end

app/views/casinos/_form.html.erb
<%= form_for(@casino) do |f| %>
  <% if @casino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casino.errors.count, "error") %> prohibited this casino from being saved:</h2>

      <ul>
      <% @casino.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
    <%= f.check_box :public %>
    <%= f.label :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/casinos/edit.html.erb
<h1>Editing casino</h1>

<%= render 'form' %>

<%= link_to 'Show', @casino %> |
<%= link_to 'Back', casinos_path %>

app/views/casinos/index.html.erb
<h1>Listing casinos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Public?</th>
    <th></th>
  </tr>

<% @casinos.each do |casino| %>
  <tr>
    <td><%= casino.name %></td>
    <td><%= casino.user.email %></td>
    <td><%= casino.public %></td>
    <td><%= link_to 'Show', casino %></td>
    <td><%= link_to 'Edit', edit_casino_path(casino) %></td>
    <td><%= link_to 'Destroy', casino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Casino', new_casino_path %>

app/views/casinos/new.html.erb
<h1>New casino</h1>

<%= render 'form' %>

<%= link_to 'Back', casinos_path %>

app/views/casinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @casino.name %>
</p>


<%= link_to 'Edit', edit_casino_path(@casino) %> |
<%= link_to 'Back', casinos_path %>