config/routes.rb
Bankroll::Application.routes.draw do
  devise_for :users
  resources :users, path: 'user_admin'

  resources :variants

  resources :casinos

  resources :public_casinos, only: :index do
    collection do
      put :set
    end
  end

  resources :games, except: :show do
    collection do
      post :import
      get :prepare_import
    end
  end

  resources :stats

  root :to => 'stats#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :buyin, :casino_id, :prize, :variant_id, :user_id
  belongs_to :casino
  belongs_to :variant
  belongs_to :user

  validates :buyin, numericality: {greater_than_or_equal_to: 0}
  validates :prize, numericality: {greater_than_or_equal_to: 0}

  def self.prizes_sum(user)
    user.games.sum(:prize) - user.games.sum(:buyin)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  # Possire_import

  # GET /games
  # GET /games.json
  def index
    @games = current_user.games

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end


  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  def prepare_import
  end

  def import
    GamesImport.new(params[:file], current_user).create_records

    redirect_to games_url, notice: 'Hry byly importovány'
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @game.user_id = current_user.id

    if @game.save
      redirect_to games_url, notice: 'Game was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to games_url, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buyin %><br />
    <%= f.number_field :buyin %>
  </div>
  <div class="field">
    <%= f.label :prize %><br />
    <%= f.number_field :prize %>
  </div>
  <div class="field">
    <%= f.label :variant_id %><br />
    <%= f.collection_select :variant_id, Variant.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :casino_id %><br />
    <%= f.collection_select :casino_id, Casino.for_user_and_visible(current_user.id), :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<%= link_to 'Import new games', prepare_import_games_path %>

<table>
  <tr>
    <th>Buy-in</th>
    <th>Prize</th>
    <th>Game variant</th>
    <th>Casino / play room</th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.buyin %></td>
    <td><%= game.prize %></td>
    <td><%= game.variant.name %></td>
    <td><%= game.casino.name %></td>
    <td><%= game.user.email %></td>
    <td><%= link_to 'Change', edit_game_path(game) %></td>
    <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Write a new game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/prepare_import.html.erb
<%= form_tag import_games_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Importovat' %>
<% end %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Buyin:</b>
  <%= @game.buyin %>
</p>

<p>
  <b>Prize:</b>
  <%= @game.prize %>
</p>

<p>
  <b>Variant:</b>
  <%= @game.variant_id %>
</p>

<p>
  <b>Casino:</b>
  <%= @game.casino_id %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>