config/routes.rb
Bankroll::Application.routes.draw do
  devise_for :users
  resources :users, path: 'user_admin'

  resources :variants

  resources :casinos

  resources :public_casinos, only: :index do
    collection do
      put :set
    end
  end

  resources :games, except: :show do
    collection do
      post :import
      get :prepare_import
    end
  end

  resources :stats

  root :to => 'stats#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :is_admin

  has_many :games
  has_many :casinos
end

app/controllers/public_casinos_controller.rb
class PublicCasinosController < SecuredController
  def index
    @casinos = Casino.where(public: true)
  end

  def set
    Casino.set_visibility(params[:casino_ids])
    redirect_to public_casinos_url, notice: 'Visibility saved.'
  end
end

app/views/public_casinos/index.html.erb
<h1>Listing casinos</h1>
<%= form_tag set_public_casinos_path, method: :put do %>
<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Visible</th>
    <th></th>
  </tr>

<% @casinos.each do |casino| %>
  <tr>
    <td><%= casino.name %></td>
    <td><%= casino.user.email %></td>
    <td><%= check_box_tag 'casino_ids[]', casino.id, casino.visible? %></td>
    <td><%= link_to 'Edit', edit_casino_path(casino) %></td>
    <td><%= link_to 'Destroy', casino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
  <%= submit_tag 'Set visibility' %>

<% end %>
<br />

<%= link_to 'New Casino', new_casino_path %>